version: '3.8'

services:
    postgres:
        image: timescale/timescaledb:latest-pg14
        environment:
            POSTGRES_PASSWORD: "eu gosto de ubuntu!"
            POSTGRES_DB: project_greenhouse
            POSTGRES_USER: vasco
        ports: 
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data   # dados persistentes do container
            - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql  # SQL versionado
        restart: unless-stopped


    mosquitto:
        image: eclipse-mosquitto:latest
        ports:
            - "1883:1883"
        volumes:
            - mqtt_data:/mosquitto/data
            - mqtt_log:/mosquitto/log
            - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
volumes:
    postgres_data:
    mqtt_data:
    mqtt_log:
